### ISSUE TITLE
Regain whiterun issues?

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#41] opened 2023-04-16 10:20 UTC
okay so basically before i start read all of this before you make any edits as everything here is related

i had completed prerequisite quests to start battle of whiterun Rikke was bugging out (see rikke has vanished) so i couldn't start the battle i went to Whiterun to find a modded follower and found this
![20230416195932_1](https://user-images.githubusercontent.com/128126252/232294734-7b5df703-4d04-48a4-b963-a2e72fad2ae2.jpg)
i knew this would start battle of Whiterun so i attempted to see if i could force it to happen. it did then i encountered issues (naturally because i didn't talk to rikke) anyway i reloaded an earlier save after i found out rikke was behind the tent (again see Rikke has vanished for details) anyway everything was normal..... until i entered the city

![20230416200854_1](https://user-images.githubusercontent.com/128126252/232295743-1b93582a-4067-4fda-9a82-1d09d1b85000.jpg)
![20230416200923_1](https://user-images.githubusercontent.com/128126252/232295754-1c50e98a-8275-4ddd-b55f-ef0bc4f16af8.jpg)
people were roaming around and i never got FORCE VIGNAR GREYMANE TO SURRENDER 

is this a bug? or did i just break it from not speaking to rikke?

**Comment by schofida** [comment] 2023-04-16 19:54
I will take a look. I think I remember in one of my tests that the barrier appeared prematurely. While everyone is running around in Whiterun can you run the following commands?

getstage cwsiege
getquestrunning cwattackcity
getstage cwattackcity

**Comment by LABWAZHERE** [comment] 2023-04-16 23:39
cw siege 60.00
get quest running 0.00
get stage 9999.00

i will note this is a save that i have just entered dragonreach vignar was acting like there wasn't a siege going on i left dragonsreach and did these
this is debug menu
![20230417093502_1](https://user-images.githubusercontent.com/128126252/232349678-f86e3078-d2e7-4890-92ac-bf22036f46cd.jpg)
this is the quest in my logbook
![20230417093914_1](https://user-images.githubusercontent.com/128126252/232349738-1789c8d0-5994-4b4c-9354-c8eb7b0cf073.jpg)

**Comment by schofida** [comment] 2023-04-17 19:32
Closing this as a duplicate of #48 The fact that cwattackcity is not starting is definitely the culprit

**Closed as completed by schofida** 2023-04-17 19:32 UTC
