### ISSUE TITLE
Offence siege of Fort Kastav (stormcloak only)

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#25] opened 2023-03-19 12:18 UTC
Siege of Fort Kastav mission isn't being given to me, don't have an active Stormcloak save so i can't get more info until i am done with the re run through of imperials, also gonna throw in the cursed clipping of the map with the shrine

Example of bug below:
![20230319095038_1](https://user-images.githubusercontent.com/128126252/226174567-d7f3e16c-1dc8-4461-841e-0d189ab3d73b.jpg)
![20230319095049_1](https://user-images.githubusercontent.com/128126252/226174574-40164c74-09d5-41b2-9e4c-6423f6cb7389.jpg)
![20230319094637_1](https://user-images.githubusercontent.com/128126252/226174764-0aa459a6-ef09-463b-8a7d-6502441df55c.jpg)

i will add i did get this with the conquest save (already turned it off at this point but there may be lingering code) so that may be the reason, still worth looking into though

on another note chill out Galmar you sounding a bit too eager

**Comment by LABWAZHERE** [comment] 2023-04-17 00:50
update; imperial version boots fine

**Comment by schofida** [comment] 2023-04-17 19:59
Closing this issue as a duplicate of #47

**Closed as completed by schofida** 2023-04-17 19:59 UTC
