### ISSUE TITLE
Re tulius not doing speech

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#72] opened 2023-04-26 05:34 UTC
I could not get tulius to do his speech 

>Keep in mind that there is a 50% chance at Markarth and Riften of Tullius showing up. Otherwise it’s just Rikke and she does the pep-talk.

About that, tulius was always appearing (at least appeared in all 4 major sieges Whiterun, Windhelm, Riften (I think) and Markarth) and his speech went off smoothly

Before the I think seasons unending update 
I have not seen him at any since then, in addition to that I have not seen him do the final speech when I teleport there it basically auto starts or they are gone

If it is 50% then that doesn’t explain why I have not seen him since
_Originally posted by @schofida in https://github.com/schofida/CWORR/issues/34#issuecomment-1509846960_

**Comment by schofida** [comment] 2023-04-26 18:02
Lucky for you, I found this yesterday. It should be fixed now.

In regards to Tullius/Ulfric not showing up ever in the major city sieges.

**Comment by LABWAZHERE** [comment] 2023-04-27 23:44
fixed they appear

**Comment by LABWAZHERE** [comment] 2023-04-28 01:05
reopening this because  enemy co officers (Rikke and Galmar) don't appear in non final stand defence battles or at least whiterun defence

**Comment by schofida** [comment] 2023-04-28 17:48
Hmm... This is a good idea. I'll try to add this. This was never added before and its not vanilla behavior (besides Rikke on the first defense of Whiterun).

**Comment by LABWAZHERE** [comment] 2023-04-28 20:55
> Hmm... This is a good idea. I'll try to add this. This was never added before and its not vanilla behavior (besides Rikke on the first defense of Whiterun).

really?
i have seen galmar in the defence of whiterun (imperials) many times

**Comment by schofida** [comment] 2023-06-11 17:09
I am unable to reproduce so I will close this. Galmar shows up to attack Riften when I am defending Riften.

**Closed as completed by schofida** 2023-06-11 17:09 UTC
