### ISSUE TITLE
Skirmish at soljunds sinkhole not completing

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#23] opened 2023-03-19 04:40 UTC
they are all dead but it 
![20230319153444_1](https://user-images.githubusercontent.com/128126252/226154015-b874a231-616f-40b3-8d0b-da46297435fd.jpg)
![20230319153458_1](https://user-images.githubusercontent.com/128126252/226154016-53083799-911d-4ac4-ab47-2e32ecb7b2ee.jpg)
![20230319153514_1](https://user-images.githubusercontent.com/128126252/226154024-de9fcb98-6f31-444b-87c1-793ad555ecfa.jpg)
won't complete...... i smell a rat, or in this case a skeever

**Comment by schofida** [comment] 2023-03-19 04:49
Can you post the CWO Debug? It should give a count as to how many troops remain. Keep in mind that there should be a pool of them that will keep respawning until the pool is exhausted (similar to how the fort/capital sieges work)....

Also just to make sure, did you tick the 'Get Civil War Unstuck' option in the MCM? That should complete it.

**Comment by LABWAZHERE** [comment] 2023-03-19 04:52
> Can you post the CWO Debug? It should give a count as to how many troops remain. Keep in mind that there should be a pool of them that will keep respawning until the pool is exhausted (similar to how the fort/capital sieges work)....
> 
![20230319155112_1](https://user-images.githubusercontent.com/128126252/226154414-e8c219dd-898a-4a41-954f-b1177c74794e.jpg)

> Also just to make sure, did you tick the 'Get Civil War Unstuck' option in the MCM? That should complete it.
doing that set up the whiterun seige it said attempting to set up whiterun siege 
![20230319155128_1](https://user-images.githubusercontent.com/128126252/226154448-4f27535a-3826-49d1-888c-b8defa66b767.jpg)
this was before ticking the box

**Comment by schofida** [comment] 2023-03-19 05:03
Thanks. So that is a skirmish on the defense. I have not looked at that in a while so I will investigate.

And it looks like ticking the 'Help get quests unstuck' did work. Completing the Skirmish should immediately start the Markarth siege defense. How all Skyrim quests work is that they start behind the scenes and then speaking to the quest giver will trigger the objective (which actually shows the quest started on the screen). For the siege defense, it starts behind the scenes and triggers the courier. (to which then reading the letter triggers the objective).

Although, I thought I didn't show the 'attempting to set up siege...' on defense :(

**Comment by LABWAZHERE** [comment] 2023-03-19 05:08
> it didn't, i did fail it because i fast travelled away then was met with a courier with a message that whiterun (which we didn't own) was under attack, when i fast travelled there it gave me the offense quest for whiterun on top of this upon completon it said imperials held control of markath

**Comment by ds-nscorp** [comment] 2023-03-19 05:13
Crap. You're right then. It sure didn't work. I have to check that routine then. Being on the defense might be tripping it up.

**Comment by LABWAZHERE** [comment] 2023-03-19 11:33
maybe, can i just ask is it possible to lose the skirmishes other than teleporting away?

**Comment by ds-nscorp** [comment] 2023-04-01 13:03
Hey it's the weekend and I finally have time to answer some of your questions 😀 So you can also lose the skirmishes by running out of HP and entering bleed out before wiping out the enemy troops. I did a defensive Skirmish at Rorikstead and it worked without a problem. This might be isolated to Soljund's Sinkhole so I'll keep trying.

**Comment by LABWAZHERE** [comment] 2023-04-01 22:00
that would make sense, i test the civil war by using god mode to get to certain points (like seasons unending) quicker

**Comment by LABWAZHERE** [comment] 2023-04-17 01:50
> This might be isolated to Soljund's Sinkhole so I'll keep trying.

NO  NOPE IT ISN'T shor stone won't complete either


UPDATE NVM BUT SHOR STONE HAS ISSUES
![20230417115032_1](https://user-images.githubusercontent.com/128126252/232359451-c3779d09-2e14-4ab8-9c11-6fd563f5a43e.jpg)
![20230417115109_1](https://user-images.githubusercontent.com/128126252/232359452-072661c2-f6d1-4874-977b-0c8e0a2bc9cb.jpg)
![20230417115126_1](https://user-images.githubusercontent.com/128126252/232359457-4d3b2beb-4c79-4d1b-b0fd-f2baab27b253.jpg)

for some reason one guy spawns in fort greenwall

**Comment by schofida** [comment] 2023-04-22 21:56
Thanks for this. I was able to reproduce and I think that I will have fixed in the next release tentatively scheduled for tomorrow.

**Comment by schofida** [comment] 2023-04-26 17:13
This should be resolved. I was able to test that this is working.

I added a safeguard to check to see if you are not in combat for more than 3 seconds. If you are not, it completes the quest.

**Closed as completed** 2023-05-14 13:55 UTC

**Comment by LABWAZHERE** [comment] 2023-05-15 03:09
One thing that makes it hard to test is there is no debug option to choose the specific towns you want to skirmish in
