### ISSUE TITLE
Death Alternative Unreliable

### ISSUE THREAD

**Issue by Eve-Knight** [schofida/CWORR#58] opened 2023-04-21 19:22 UTC
Tried to take Falkreath from the empire. Took fatal damage and just got the normal load screen and automatic loading of last save. (As a side note, even with whatever level-based content now exists, it's extremely challenging on novice). Tried again. Similar result the second time. Only the third time did it actually give me a message about how I couldn't go on and respawn me in a Stormcloak camp instead.

**Comment by schofida** [comment] 2023-04-21 21:12
That is very peculiar. So what is supposed to happen is once the battle starts, there should be a death monitor that marks the player as essential (can't die). Can you do me a favor and check the MCM CWO Debugger and ensure that that there is a 'Player Bleedout Monitor Is On' status. If there is and it is still causing you to die, then that is a Skyrim engine issue although I can say that I don't remember this happening to me.

If possible, can you add the following to your Skyrim.ini or SkyrimCustom.ini (I know how to do this in Mod Organizer if you need assistance)? What it should do is enable papyrus script logging and will greatly assist in tracking down these issues especially if I cannot reproduce. (And once you're done, set these values back to 0 because Skyrim's engine is terrible :( and logging text to files causes framerate issues)

[Papyrus]
bEnableLogging=1
bEnableProfiling=1
bEnableTrace=1
bLoadDebugInformation = 1

In your remark to the enemies being too hard, you might be right. Can you let me know what character level you are? I want to say that you want to be at least level 10 and decently geared before attempting the Civil War.

**Comment by Eve-Knight** [comment] 2023-04-21 21:58
The debug tab how no mention of bleedout, but I'm not currently in a civil war battle. I'll take a look here next time so we can tell if it's failing to turn it on or if it's failing to work when it is on.

INI modified as directed for future issues.

My character was about Level 24 with Goldbrand, Civil War Champion and Ebony Spell Knight armor. I've also noticed that at least some of the new units seem to hurt way more than even enemies triple their level. For example, the random event where Imperials escort a Stormcloak prisoner has spawned for me with the new archers and wizards that your mod adds; this made the encounter go from pushover (on novice) to barely surviving, despite their actual level being synced to mine in this case (which was 6 at the time).

**Comment by ds-nscorp** [comment] 2023-04-21 22:08
Thanks for letting me know. I play Requiem so balance-wise I don't really know what I am doing lol. I do want the Civil War troops to be properly perked like other NPCs in Skyrim. But I will see what I can do to tone things down some.

**Comment by Eve-Knight** [comment] 2023-04-25 00:56
I wonder if PC Head Tracking's bleedout bug fix might interfere.

**Comment by schofida** [comment] 2023-04-26 17:57
If it does, that stinks. (I love that mod) I will investigate.

**Comment by schofida** [comment] 2023-05-04 16:50
> Thanks for letting me know. I play Requiem so balance-wise I don't really know what I am doing lol. I do want the Civil War troops to be properly perked like other NPCs in Skyrim. But I will see what I can do to tone things down some.

@Eve-Knight @LABWAZHERE Just letting you both know that I am primarily focused on this task right now. I am having a bear of a time trying to make this all work properly but I am making progress. I will hopefully have an update by the end of the week.

**Comment by schofida** [comment] 2023-05-14 13:58
@Eve-Knight The latest release should have adjusted troops so things should hopefully be a little more balanced now. Can you give it a try?

**Comment by Eve-Knight** [comment] 2023-05-14 16:15
Sure.

**Comment by Eve-Knight** [comment] 2023-05-18 01:20
Battle went well this time around. My own character was also more powerful this time, but it was an easy win on novice, so I think we're good.

**Comment by schofida** [comment] 2023-05-28 02:45
Thanks! I will close this. I will make a note that there may be a minor conflict between the bleed out mechanic and PC Headtracking

**Closed as completed by schofida** 2023-05-28 02:45 UTC
