### ISSUE TITLE
Whiterun defence battles not playing - possible Conquest of Skyrim Conflict unsure as of yet

### ISSUE THREAD

**Issue by LABWAZHERE** [schofida/CWORR#16] opened 2023-03-18 23:58 UTC
neither side can retake whiterun did you add the defence battles for whiterun?

**Comment by schofida** [comment] 2023-03-19 04:34
Thanks for reporting this. This might be another issue to chalk up to ensuring that the dialogue conditions are correct. So just to make sure, you were given the note by the courier. And you were then given the objective to speak with the Field CO in Whiterun. But they then didn't have anything to say?

**Comment by LABWAZHERE** [comment] 2023-03-19 04:36
no i didnt get that far, no courier. When i retook winterhold i couldn't start up a siege quest for whiterun at all it only forced started up the next hold. (falkreath)

edit: this may have been a conflict with conquest of Skyrim, forgot i had it active at the time, i usually turn it off for the civil war. this is the first time in a long time i have done the civil war quest so i forgot i had it active.

When i get home i will test to make sure i can do it on the non conquest save to make sure it isn't a mod conflict

**Comment by schofida** [comment] 2023-03-31 13:38
@LABWAZHERE  So I was unable to reproduce. I was able to get the Defense of Whiterun to come up just fine but I did fix a bunch of issues when it came to the defense (primarily with objectives coming up). I posted a new version in the Releases section

As an aside, can you send me the Conquest of Skyrim link? I will see if I can check for conflicts.

**Comment by LABWAZHERE** [comment] 2023-03-31 22:28
i apologize for that i forgot it had conflicts, i am a former xbox player so i forgot about the conflicts conquest had, also forgot to disable it before it
https://www.nexusmods.com/skyrimspecialedition/mods/65628

another thing to note is this from the mod page
"At the moment I can not guarantee compatibility of this mod with any mod pertaining to the civil war or uses NPCs that you intend to recruit. It is recommended you not start your faction unless you either have no intention of doing the civil war questline or have already completed it. Remember that this is a WIP and I will add compatibility patches later.

it suggests the mod should still be playable until you start a faction so i don't know why it makes ulfric immortal

**Comment by LABWAZHERE** [comment] 2023-04-15 00:41
update update: uh yeah i could not reproduce this in later releases, i did have conquest active but i dont think it was the cause but it could have contributed to it. i remember what happened better so i will elaborate a bit more, everything was normal, until the first battle of whiterun, It said Battle of Whiterun: FAILED and it said the courier was dispatched (i think) i don't remember if i was stormcloak or imperial but i think i was Imperial then it for some reason happened again the battle started up again, Started: Battle for Whiterun i do not remember if i teleported away or if i didn't (before second boot up) This probably contributed to the inability to take Winterhold. everything was working fine again until i was able to take all the holds except Whiterun which i had to do via mcm. 

i have no clue what happened and i have not had this happen again with and without conquest. i have no clue what happened, i am busy right now but i will try again with conquest and see if i can reproduce it. i do not have access to the save file as i purge my save files every so often as to clear left over code for most like conquest. i do have saves that do not have conquest now so i just disable conquest and use those but i had to purge the original file

**Comment by schofida** [comment] 2023-04-22 21:53
Marking this as closed for now. It looks like this is not (consistently happening anymore)

**Closed as completed by schofida** 2023-04-22 21:53 UTC
